# Generated by Django 4.2.11 on 2024-04-11 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('abilityID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('affect', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='EleType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('effective', models.ManyToManyField(to='pokedex.eletype')),
                ('weakness', models.ManyToManyField(to='pokedex.eletype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('classification', models.TextField()),
                ('image_link', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('abilities', models.ManyToManyField(to='pokedex.ability')),
                ('prevevolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('type', models.ManyToManyField(to='pokedex.eletype')),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('favorites', models.ManyToManyField(to='pokedex.pokemon')),
            ],
        ),
    ]
