# Generated by Django 4.2.11 on 2024-04-21 04:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('abilityID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
                ('affect', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='EleType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('effective', models.ManyToManyField(blank=True, related_name='+', to='pokedex.eletype')),
                ('no_effect_on', models.ManyToManyField(blank=True, related_name='+', to='pokedex.eletype')),
                ('weakness', models.ManyToManyField(blank=True, to='pokedex.eletype')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('classification', models.TextField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('abilities', models.ManyToManyField(to='pokedex.ability')),
                ('prevevolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('favorites', models.ManyToManyField(to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pokeimages')),
                ('description', models.CharField(max_length=64)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
            options={
                'unique_together': {('pokemon', 'description')},
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='primary_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_image_of', to='pokedex.pokemonimage'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokedex.eletype'),
        ),
    ]
