# Generated by Django 4.2.11 on 2024-04-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletype',
            name='effective',
            field=models.ManyToManyField(blank=True, to='pokedex.eletype'),
        ),
        migrations.AlterField(
            model_name='eletype',
            name='weakness',
            field=models.ManyToManyField(blank=True, to='pokedex.eletype'),
        ),
    ]
