# Generated by Django 4.2.11 on 2024-04-11 22:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_ability_alter_pokemon_options_eletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='PrevEvolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='classification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='image_link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('ranking', models.ManyToManyField(to='pokedex.pokemon')),
            ],
        ),
    ]
