# Generated by Django 4.2.11 on 2024-04-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_prevevolution_pokemon_classification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletype',
            name='Pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='Type',
            field=models.ManyToManyField(to='pokedex.eletype'),
        ),
    ]
