# Generated by Django 4.2.11 on 2024-04-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_eletype_effective_alter_eletype_weakness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletype',
            name='effective',
            field=models.ManyToManyField(blank=True, null=True, to='pokedex.eletype'),
        ),
        migrations.AlterField(
            model_name='eletype',
            name='weakness',
            field=models.ManyToManyField(blank=True, null=True, to='pokedex.eletype'),
        ),
    ]
