# Generated by Django 4.2.11 on 2024-04-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_prevevolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='prevevolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon'),
        ),
    ]
