# Generated by Django 4.2.11 on 2024-04-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_auto_20240421_0417'),
    ]

    operations = [
    ]
