# Generated by Django 4.2.11 on 2024-04-21 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0013_auto_20240421_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='primary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_image_of', to='pokedex.pokemonimage'),
        ),
    ]
