# Generated by Django 4.2.11 on 2024-04-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_alter_pokemon_primary_image'),
    ]

    operations = [
    ]
