# Generated by Django 4.2.11 on 2024-04-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0015_auto_20240421_0423'),
    ]

    operations = [
    ]
