# Generated by Django 4.2.11 on 2024-04-26 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0019_alter_pokemonimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='prevevolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postevolutions', to='pokedex.pokemon'),
        ),
    ]
