# Generated by Django 4.2.11 on 2024-04-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='co_number',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
